spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/akdenizbankdb
    username: root
    password: 159632
    driver-class-name: com.mysql.cj.jdbc.Driver